"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def main():
	fibonacci_evens = get_fibonacci_evens()
	final_sum = sum(fibonacci_evens)
	print("Sum of even Fibonacci sequence values under 4 million: {}".format(final_sum))

def get_fibonacci_evens():
	sequence = [2]
	a = 1
	b = 2
	next_number = 0
	while next_number < 4e6:
		next_number = a + b
		if next_number % 2 == 0:
			sequence.append(next_number)
		a = b
		b = next_number
	return sequence

main()
