"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
DIVISOR_LIMIT = 500

def main():
	divisors = []
	triangle_number = 0
	counter = 1

	while len(divisors) <= DIVISOR_LIMIT:
		triangle_number += counter
		divisors = get_divisors(triangle_number)
		counter += 1

	print("The first triangle number with at least {} divisors is: {}".format(DIVISOR_LIMIT, triangle_number))

def get_divisors(number):
	divosors = set()
	for x in range(1, number+1):
		if number%x == 0:
			divosors.add(x)
			divosors.add(number/x)
	return divosors

main()